// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from './etc';
import type { FullModifier } from './modifiers';
import type {
  FullSense,
  FullSpeedTrait,
  Immunity,
  Language,
  Profession,
} from './other_info';
import type { FullAncestry, FullPath } from './path';

export type CharacterIndexItem = {
  id: number;
  name: string;
  level: number;
  ancestry: string;
  novice_path: string;
  expert_path: string | null;
  master_path: string | null;
};

export type CreateCharacter = {
  name: string;
  profession_id: number;
  ancestry_id: number;
  novice_path_id: number;
  strength: number;
  agility: number;
  intellect: number;
  will: number;
};

export type FullCharacter = {
  id: number;
  name: string;
  level: number;
  health: number;
  damage: number;
  strength: number;
  agility: number;
  intellect: number;
  will: number;
  profession: Profession;
  ancestry: FullAncestry;
  novice_path: FullPath;
  expert_path: FullPath | null;
  master_path: FullPath | null;
  created_at: string;
  max_health: number;
  nat_def: number;
  arm_def: number;
  speed: number;
  bonus_dmg: number;
  speed_traits: Array<FullSpeedTrait>;
  senses: Array<FullSense>;
  immunities: Array<Immunity>;
  languages: Array<Language>;
  size: Size;
  choices: Array<FullModifier>;
};
