// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullAncestry, FullPath } from './path';

export type CharacterIndexItem = {
  id: number;
  name: string;
  level: number;
  ancestry: string;
  novice_path: string;
  expert_path: string | null;
  master_path: string | null;
};

export type FullCharacter = {
  id: number;
  name: string;
  level: number;
  strength: number;
  agility: number;
  intellect: number;
  will: number;
  ancestry: FullAncestry;
  novice_path: FullPath;
  expert_path: FullPath | null;
  master_path: FullPath | null;
  choices: null;
};
