// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullChoice } from './choice_selections';
import type { Size } from './etc';
import type { FullMagicTalent, FullSpell, TraditionIndexItem } from './magic';
import type { FullModifier } from './modifiers';
import type {
  FullSense,
  FullSpeedTrait,
  Language,
  Profession,
} from './other_info';
import type { FullAncestry, FullPath, FullPathTalent } from './path';

export type CharacterIndexItem = {
  id: number;
  name: string;
  level: number;
  ancestry: string;
  novice_path: string;
  expert_path: string | null;
  master_path: string | null;
};

export type CreateCharacter = {
  name: string;
  profession_id: number;
  ancestry_id: number;
  novice_path_id: number;
  strength: number;
  agility: number;
  intellect: number;
  will: number;
};

export type FullCharacter = {
  id: number;
  name: string;
  level: number;
  health: number;
  damage: number;
  strength: number;
  agility: number;
  intellect: number;
  will: number;
  profession: Profession;
  ancestry: FullAncestry;
  novice_path: FullPath;
  expert_path: FullPath | null;
  master_path: FullPath | null;
  created_at: string;
  max_health: number;
  nat_def: number;
  arm_def: number;
  speed: number;
  bonus_dmg: number;
  traditions: Array<[TraditionIndexItem, string]>;
  speed_traits: Array<[FullSpeedTrait, string]>;
  senses: Array<[FullSense, string]>;
  immunities: Array<[string, string]>;
  languages: Array<[Language, string]>;
  size: Size;
  path_talents: Array<[FullPathTalent, string]>;
  magic_talents: Array<[FullMagicTalent, string]>;
  spells: Array<[FullSpell, string]>;
  modified_slots: Array<SlotMod>;
  required_choices: Array<FullModifier>;
  selected_choices: Array<[FullModifier, Array<FullChoice>]>;
};

export type SlotMod =
  | { Plus: { amount: number; spell_id: number } }
  | { Times: { amount: number; spell_id: number } };
