// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullModifier } from './modifiers';

export type ChoiceTable = {
  id: number;
  name: string;
  choices: Array<FullChoice>;
};

export type FullChoice = {
  id: number;
  label: string | null;
  description: string;
  modifiers: Array<FullModifier>;
};
