// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathKind = 'Novice' | 'Expert' | 'Master';

export type Size = 'Sm' | 'Md' | 'Lg';

export type TalentRestore =
  'None' | 'LuckEnds' | 'Rest' | 'Day' | 'Hour' | 'Minute';
