// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportEvent =
  | { type: 'Ready'; data: ImportSummary }
  | { type: 'Progress'; data: ProgressPayload }
  | { type: 'Done' };

export type ImportSummary = {
  ancestries: number;
  languages: number;
  speed_traits: number;
  senses: number;
  profession_categories: number;
  professions: number;
  traditions: number;
  magic_talents: number;
  magic_spells: number;
  novice_paths: number;
  novice_levels: number;
  expert_paths: number;
  expert_levels: number;
  master_paths: number;
  master_levels: number;
  path_talents: number;
  options: number;
  tables: number;
};

export type ProgressPayload = [number, number];
