// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportEvent =
  | { type: 'Ready'; data: ReadyPayload }
  | { type: 'Progress'; data: ProgressPayload }
  | { type: 'Done' };

export type ProgressPayload = [number, number];

export type ReadyPayload = { ancestries: number };
