// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Entry = { key: string; value: string };

export type FullInfoTable = {
  id: number;
  name: string;
  kind: TableKind;
  key_label: string;
  value_label: string;
  entries: Array<Entry>;
};

export type TableKind = 'TABLE' | 'BLOCK' | 'ROLL';
