// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind, TalentRestore } from './etc';
import type { FullInfoTable } from './info_tables';
import type { FullOptionBlock } from './option_blocks';

export type FullMagicTalent = {
  id: number;
  tradition_id: number;
  tradition_name: string;
  name: string;
  description: string;
  charges: string | null;
  restore: TalentRestore;
  activate: string;
  info_table_id: FullInfoTable | null;
  option_block_id: FullOptionBlock | null;
};

export type FullSpell = {
  id: number;
  tradition_id: number;
  tradition_name: string;
  name: string;
  description: string;
  path_kind: PathKind;
  castings: number;
  duration: string;
  target: string;
  condition: string | null;
  ritual: boolean;
  info_table: FullInfoTable | null;
  option_block: FullOptionBlock | null;
};

export type FullTradition = {
  id: number;
  name: string;
  blurb: string;
  description: string;
  special_info: string | null;
  into_table: FullInfoTable | null;
};
