// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplySlotsTarget =
  | { type: 'AnySpell'; data: number }
  | { type: 'NoviceSpell'; data: number }
  | { type: 'ExpertSpell'; data: number }
  | { type: 'MasterSpell'; data: number }
  | { type: 'Tradition'; data: [number, string] }
  | { type: 'SpecificSpell'; data: [number, string, string] };

export type ApplyTarget =
  | { type: 'Heal'; data: HealAmount }
  | { type: 'Health'; data: HealAmount }
  | { type: 'Slots'; data: ApplySlotsTarget };

export type ChooseSlotTarget =
  { type: 'Plus'; data: number } | { type: 'Times'; data: number };

export type ChooseTarget =
  | { type: 'Language'; data: number }
  | { type: 'Profession'; data: number }
  | { type: 'Tradition'; data: number }
  | { type: 'NoviceSpell'; data: number }
  | { type: 'NoviceSpellFrom'; data: [number, Array<string>] }
  | { type: 'ExpertSpell'; data: number }
  | { type: 'ExpertSpellFrom'; data: [number, Array<string>] }
  | { type: 'MasterSpell'; data: number }
  | { type: 'MasterSpellFrom'; data: [number, Array<string>] }
  | { type: 'Select'; data: [number, string] }
  | { type: 'Score'; data: number }
  | { type: 'Slots'; data: ChooseSlotTarget }
  | { type: 'MagicTalent'; data: [number, Array<string>] };

export type Condition =
  | { type: 'None' }
  | { type: 'HasNot' }
  | { type: 'Has'; data: HasCategory }
  | { type: 'If'; data: SimpleExpr };

export type Dice = { die_size: number; die_count: number };

export type ExprOp =
  | { type: 'Lt' }
  | { type: 'Gt' }
  | { type: 'LtEq' }
  | { type: 'GtEq' }
  | { type: 'Eq' }
  | { type: 'Div' };

export type ExprValue =
  | { type: 'Health' }
  | { type: 'Dmg' }
  | { type: 'Level' }
  | { type: 'Defense' }
  | { type: 'Number'; data: number };

export type FullModifier = {
  path_node: ModifierPathNode;
  mod_details: Modifier;
};

export type GrantTarget =
  | { type: 'Int'; data: number }
  | { type: 'Str'; data: number }
  | { type: 'Will'; data: number }
  | { type: 'Agl'; data: number }
  | { type: 'Speed'; data: number }
  | { type: 'Health'; data: number }
  | { type: 'Defense'; data: number }
  | { type: 'NatDef'; data: number }
  | { type: 'BonusDamage'; data: number }
  | { type: 'Language'; data: Array<string> }
  | { type: 'Tradition'; data: Array<string> }
  | { type: 'Immunity'; data: Array<string> }
  | { type: 'Sense'; data: Array<[string, string | null]> }
  | { type: 'SpeedTrait'; data: Array<[string, string | null]> }
  | { type: 'Talent'; data: [string, string] }
  | { type: 'MagicTalent'; data: [string, string] };

export type HasCategory =
  { type: 'SpeedTrait'; data: string } | { type: 'Sense'; data: string };

export type HealAmount =
  | { type: 'Number'; data: number }
  | { type: 'Expr'; data: SimpleExpr }
  | { type: 'Roll'; data: Dice }
  | { type: 'Ask'; data: string };

export type LoseTarget =
  | { type: 'Talent'; data: [string, string] }
  | { type: 'MagicTalent'; data: [string, string] };

export type Modifier = { when: WhenMod; target: Target; condition: Condition };

export type ModifierPathNode =
  | { type: 'LevelLanguage'; data: { path_name: string; level: number } }
  | { type: 'LevelTradition'; data: { path_name: string; level: number } }
  | { type: 'LevelMagicTalent'; data: { path_name: string; level: number } }
  | { type: 'LevelNoviceSpell'; data: { path_name: string; level: number } }
  | { type: 'LevelExpertSpell'; data: { path_name: string; level: number } }
  | { type: 'LevelMasterSpell'; data: { path_name: string; level: number } }
  | { type: 'LevelScore'; data: { level: number } }
  | {
      type: 'PathTalent';
      data: { name: string; source: string; granter: string; idx: number };
    }
  | {
      type: 'MagicTalent';
      data: { name: string; tradition: string; idx: number };
    }
  | { type: 'Spell'; data: { name: string; tradition: string; idx: number } }
  | {
      type: 'ChoiceSelection';
      data: { name: string; label: string; idx: number };
    };

export type OverrideTarget =
  | { type: 'Speed'; data: number }
  | { type: 'Defense'; data: number }
  | { type: 'StatBlock'; data: string }
  | { type: 'MergeStatBlock'; data: [string, string] };

export type SimpleExpr = { left: ExprValue; right: [ExprOp, ExprValue] | null };

export type Target =
  | { type: 'Grant'; data: GrantTarget }
  | { type: 'Lose'; data: LoseTarget }
  | { type: 'Override'; data: OverrideTarget }
  | { type: 'Choose'; data: [ChooseTarget, Array<string>] }
  | { type: 'Apply'; data: ApplyTarget };

export type WhenDuration =
  | { type: 'OneMinute' }
  | { type: 'OneHour' }
  | { type: 'FourHours' }
  | { type: 'EightHours' }
  | { type: 'OneDay' }
  | { type: 'Rest' };

export type WhenMod =
  | { type: 'Permanent' }
  | { type: 'CastOnce' }
  | { type: 'CastTime'; data: WhenDuration }
  | { type: 'CastTimeDismiss'; data: WhenDuration };
