// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplySlotsTarget =
  | { AnySpell: number }
  | { NoviceSpell: number }
  | { ExpertSpell: number }
  | { MasterSpell: number }
  | { Tradition: [number, string] }
  | { SpecificSpell: [number, string, string] };

export type ApplyTarget =
  { Heal: HealAmount } | { Health: HealAmount } | { Slots: ApplySlotsTarget };

export type ChooseSlotTarget = { Plus: number } | { Times: number };

export type ChooseTarget =
  | { Language: number }
  | { Profession: number }
  | { Tradition: number }
  | { NoviceSpell: number }
  | { NoviceSpellFrom: [number, Array<string>] }
  | { ExpertSpell: number }
  | { ExpertSpellFrom: [number, Array<string>] }
  | { MasterSpell: number }
  | { MasterSpellFrom: [number, Array<string>] }
  | { Select: [number, string] }
  | { SelectAgain: [number, string] }
  | { Score: number }
  | { Slots: ChooseSlotTarget }
  | { MagicTalent: [number, string] };

export type Condition =
  'None' | 'HasNot' | { Has: HasCategory } | { If: SimpleExpr };

export type Dice = { die_size: number; die_count: number };

export type ExprOp = 'Lt' | 'Gt' | 'LtEq' | 'GtEq' | 'Eq' | 'Div';

export type ExprValue =
  'Health' | 'Dmg' | 'Level' | 'Defense' | { Number: number };

export type FullModifier = { path_str: string; mod_details: Modifier };

export type GrantTarget =
  | { Int: number }
  | { Str: number }
  | { Will: number }
  | { Agl: number }
  | { Speed: number }
  | { Health: number }
  | { Defense: number }
  | { NatDef: number }
  | { BonusDamage: number }
  | { Language: Array<string> }
  | { Tradition: Array<string> }
  | { Sense: Array<string> }
  | { Immunity: Array<string> }
  | { SpeedTrait: Array<string> }
  | { Talent: [string, string] }
  | { MagicTalent: [string, string] };

export type HasCategory = { SpeedTrait: string } | { Sense: string };

export type HealAmount =
  { Number: number } | { Expr: SimpleExpr } | { Roll: Dice } | { Ask: string };

export type LoseTarget =
  { Talent: [string, string] } | { MagicTalent: [string, string] };

export type Modifier = { when: WhenMod; target: Target; condition: Condition };

export type OverrideTarget =
  | { Speed: number }
  | { Defense: number }
  | { StatBlock: string }
  | { MergeStatBlock: [string, string] };

export type SimpleExpr = { left: ExprValue; right: [ExprOp, ExprValue] | null };

export type Target =
  | { Grant: GrantTarget }
  | { Lose: LoseTarget }
  | { Override: OverrideTarget }
  | { Choose: [ChooseTarget, Array<string>] }
  | { Apply: ApplyTarget };

export type WhenDuration =
  'OneMinute' | 'OneHour' | 'FourHours' | 'EightHours' | 'OneDay' | 'Rest';

export type WhenMod =
  | 'Permanent'
  | 'CastOnce'
  | { CastTime: WhenDuration }
  | { CastTimeDismiss: WhenDuration };
