// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Immunity = { id: number; name: string };

export type Language = {
  id: number;
  name: string;
  description: string;
  secret: boolean;
};

export type Profession = {
  id: number;
  name: string;
  description: string;
  category: string;
};

export type ProfessionCategory = {
  id: number;
  name: string;
  description: string;
};

export type Sense = {
  id: number;
  name: string;
  description: string;
  unit: string | null;
};

export type SpeedTrait = {
  id: number;
  name: string;
  description: string;
  unit: string | null;
};
