// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from './etc';
import type { Immunity, Language } from './other_info';

export type Ancestry = {
  id: number;
  name: string;
  descriptor: string | null;
  size: Size;
  speed: number;
  add_health: number | null;
  add_nat_def: number | null;
};

export type AncestrySense = {
  id: number;
  name: string;
  description: string;
  unit: string | null;
  amount: string | null;
};

export type AncestrySpeedTrait = {
  id: number;
  name: string;
  description: string;
  unit: string | null;
  amount: string | null;
};

export type FullAncestry = {
  id: number;
  name: string;
  descriptor: string | null;
  size: Size;
  speed: number;
  add_health: number | null;
  add_nat_def: number | null;
  languages: Array<Language>;
  immunities: Array<Immunity>;
  speed_traits: Array<AncestrySpeedTrait>;
  senses: Array<AncestrySense>;
};
