// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind, Size, TalentRestore } from './etc';
import type { FullInfoTable } from './info_tables';
import type { FullOptionBlock } from './option_blocks';
import type { FullSpeedTrait, Immunity, Language } from './other_info';

export type AncestrySense = {
  id: number;
  name: string;
  description: string;
  unit: string | null;
  amount: string | null;
};

export type FullAncestry = {
  id: number;
  name: string;
  descriptor: string | null;
  size: Size;
  speed: number;
  add_health: number;
  add_nat_def: number;
  languages: Array<Language>;
  immunities: Array<Immunity>;
  speed_traits: Array<FullSpeedTrait>;
  senses: Array<AncestrySense>;
  talents: Array<FullPathTalent>;
};

export type FullLevel = {
  id: number;
  path_id: number;
  level: number;
  add_health: number;
  add_nat_def: number;
  add_arm_def: number;
  add_bonus_dmg: number;
  add_speed: number;
  trad_choices: number;
  lang_choices: number;
  novice_spells: number;
  expert_spells: number;
  master_spells: number;
  size: Size | null;
  languages: Array<string>;
  path_talents: Array<FullPathTalent>;
  speed_traits: Array<FullSpeedTrait>;
  traditions: Array<LevelTradition>;
};

export type FullPath = {
  id: number;
  name: string;
  path_kind: PathKind;
  category: string;
  description: string;
  levels: Array<FullLevel>;
};

export type FullPathTalent = {
  id: number;
  name: string;
  source: string;
  magical: boolean;
  charges: string | null;
  restore: TalentRestore;
  activate: string | null;
  description: string;
  info_table: FullInfoTable | null;
  option_block: FullOptionBlock | null;
  mod_str: string | null;
  cluster: string | null;
};

export type LevelTradition = { name: string; blurb: string };

export type NovicePath = {
  id: number;
  name: string;
  path_kind: PathKind;
  category: string;
  description: string;
  levels: Array<FullLevel>;
  rec_str: number;
  rec_agl: number;
  rec_int: number;
  rec_will: number;
  ancestry: PathAncestry | null;
};

export type PathAncestry = { id: number; name: string };

export type PathIndexItem = {
  id: number;
  name: string;
  path_kind: PathKind;
  category: string;
  description: string;
};

export type RawAncestry = {
  id: number;
  name: string;
  descriptor: string | null;
  size: Size;
  speed: number;
  add_health: number | null;
  add_nat_def: number | null;
};
